# Generated by Django 3.1.2 on 2020-11-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comic', models.CharField(max_length=120)),
                ('codigo_comic', models.CharField(max_length=12)),
                ('precio', models.CharField(max_length=7)),
                ('editorial', models.CharField(max_length=21)),
                ('autor', models.CharField(max_length=120)),
                ('cantidad', models.IntegerField(default=0)),
                ('ingreso_fecha', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
